#!/bin/bash
DIRECTORY="$(readlink -f "$(dirname "$(dirname "$(dirname "$0")")")")"
AppName="$(cat $DIRECTORY/data/info/appname.inf)"
step=1

#load functions
source "${DIRECTORY}/scripts/functions" || error "failed to source ${DIRECTORY}/scripts/functions"

function SetupWindow {
  yad --separator='\n' --title="How to use $AppName Part:$step" --image-on-top --image="${DIRECTORY}/icons/firstuse/1.png" --center --width='300' --height='300' --text-align="center" --text="Click the '+' button to add a task or reminder." --window-icon="${DIRECTORY}/icons/logo.png" --button=Exit!"${DIRECTORY}/icons/exit.png"!'Exit':4 --button='Next'!"${DIRECTORY}/icons/forward.png"!'Continue.':5

  button=$? #get exit code to determine which button was pressed.

  if [ $button -eq 4 ];then
    echo "True" > $DIRECTORY/data/info/opd
  elif [ $button -eq 5 ];then
    step=$((step+1))
    yad --separator='\n' --title="How to use $AppName Part:$step" --image="${DIRECTORY}/icons/firstuse/1.png" --center --width='300' --height='300' --text-align="center" --text="Click the '-' button to remove a task or reminder." --window-icon="${DIRECTORY}/icons/logo.png" --button=Exit!"${DIRECTORY}/icons/exit.png"!'Exit':6 --button='Next'!"${DIRECTORY}/icons/forward.png"!'Continue.':7
    button=$? #get exit code to determine which button was pressed.
    if [ $button -eq 6 ];then
      yad --separator='\n' --title="How to use $AppName Part:$step" --image="${DIRECTORY}/icons/firstuse/1.png" --center --width='300' --height='300' --text-align="center" --text="" --window-icon="${DIRECTORY}/icons/logo.png" --button=Exit!"${DIRECTORY}/icons/exit.png"!'Exit':6 --button='Next'!"${DIRECTORY}/icons/forward.png"!'Continue.':7
    elif [ $button -eq 7 ];then
      step=$((step+1))
      yad --separator='\n' --title="How to use $AppName Part:$step" --image="${DIRECTORY}/icons/firstuse/1.png" --center --width='300' --height='300' --text-align="center" --text="" --window-icon="${DIRECTORY}/icons/logo.png" --button=Exit!"${DIRECTORY}/icons/exit.png"!'Exit':8 --button='Next'!"${DIRECTORY}/icons/forward.png"!'Continue.':9
      echo "True" > $DIRECTORY/data/info/opd
    elif [ $button -eq 252 ];then
      echo "True" > $DIRECTORY/data/info/opd
      echo "User exited"
    fi
  elif [ $button -eq 252 ];then
    echo "True" > $DIRECTORY/data/info/opd
    echo "User exited"
  else
    error "Unkown button input recived: $button"
  fi
}

yad --separator='\n' --title="How to use $AppName" --center --width='300' --height='300' --text-align="center" --text="Welcome to $AppName! \n This tool will help guide you through using $AppName." --window-icon="${DIRECTORY}/icons/logo.png" --button=Cancel!"${DIRECTORY}/icons/exit.png"!'Exit':0 --button='Next'!"${DIRECTORY}/icons/forward.png"!'Continue.':1

button=$? #get exit code to determine which button was pressed.

if [ $button -eq 0 ];then
  echo "True" > $DIRECTORY/data/info/opd
elif [ $button -eq 1 ];then
  SetupWindow
elif [ $button -eq 252 ];then
  echo "True" > $DIRECTORY/data/info/opd
else
  error "Unkown button input recived: $button"
fi
