#!/bin/bash

#Functions
function error {
  echo -e "\e[91m$1\e[39m"
  exit 1
}

function CheckTask {
  while IFS='|' read -r Name Date _; do
      if [[ $Name || $Date ]]; then
          items+=( "$Name" "$Date" )
      else
          items+=( "None" "None" )
      fi
  done < <(sort -t'|' -k2 $DIRECTORY/Tasks/Tasks.txt)
  local selected="--list --separator= --column=Task/Reminder "${items[1]}" --column=Date "${items[2]}""
  eval $Tasks="'$selected'"
}
