#!/bin/bash

#Functions
function error {
  echo -e "\e[91m$1\e[39m"
  exit 1
}

function CheckTask {
  while IFS='|' read -r Name Date _; do
      if [[ $Name || $Date ]]; then
          items+=( "$Name" "$Date" )
      else
          items+=( "None" "None" )
      fi
  done < <(sort -t'|' -k2 $DIRECTORY/Tasks/Tasks.txt)
  echo "--column=Task/Reminder "${items[0]}" --column=Date "${items[1]}""
}
