#!/bin/bash

#Functions

function error {
  echo -e "\e[91m$1\e[39m"
  exit 1
}

function CheckTask {
  while IFS='|' read -r Name Date Date1 Date2 Date3 Date4 Date5 Date6 Date7 _; do
      if [[ $Name || $Date ]]; then
          items+=( "$Name" "$Date $Date1 $Date2 $Date3 $Date4 $Date5 $Date6 $Date7" )
      else
          items+=( "None" "None" )
      fi
  done < <(sort -t'|' -k2 $DIRECTORY/Tasks/Tasks.txt)
  selected="--list --separator= --column=Task/Reminder --column=Date "${items[@]}""
}
